# Generated by Django 3.1.2 on 2020-10-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timeslot', models.CharField(choices=[('a', '9:00 am - 9:30 am'), ('b', '9:31 am - 10:00 am'), ('c', '10:01 am - 10:30 am'), ('d', '10:31 am - 11:00 am'), ('e', '11:01 am - 11:30 am'), ('f', '11:31 am - 12:00 pm'), ('g', '12:01 pm - 12:30 pm'), ('h', '12:31 pm - 1:00 pm'), ('i', '1:01 pm - 1:30 pm'), ('j', '1:31 pm - 2:00 pm'), ('k', '2:01 pm - 2:30 pm'), ('l', '2:31 pm - 3:00 pm'), ('m', '3:01 pm - 3:30 pm'), ('n', '\t3:31 pm - 4:00 pm'), ('o', '4:01 pm - 4:30 pm'), ('p', '4:31 pm - 5:00 pm'), ('q', '\t5:01 pm - 5:30 pm'), ('r', '\t5:31 pm - 6:00 pm'), ('s', '\t6:01 pm - 6:30 pm'), ('t', '6:31 pm - 7:00 pm')], max_length=30)),
                ('servicetype', models.CharField(choices=[('service1', 'Service-1'), ('service2', 'Service-2'), ('service3', 'Service-3'), ('service4', 'Service-4'), ('service5', 'Service-5')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DateFulfilled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('isFull', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
