# Generated by Django 3.1.2 on 2020-10-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_datefulfilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datefulfilled',
            name='date',
            field=models.DateField(),
        ),
    ]
